#!/usr/bin/env bash

set -e

if [[ "$OSTYPE" == "darwin"* ]]; then
  # install homebrew
  if [ -n "$(which brew)" ]; then
    echo "Homewbrew is installed, skipping."
  else
    echo "Installing homebrew..."
    /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [ "$arch" == "arm64" ]; then
      eval "$(/opt/homebrew/bin/brew shellenv)"
    else
      eval "$(/usr/local/bin/brew shellenv)"
    fi
    brew analytics off
  fi

  # install ansible
  if [ -n "$(which ansible)" ]; then
    echo "Ansible is installed, skipping."
  else
    echo "Installing ansible..."
    brew install ansible
  fi
else
  echo "Unsupported OS type!"
  exit 1
fi
