- name: Install CLI apps
  homebrew:
    name:
      - colima
      - docker
      - mise
      - tmux
- name: Install GUI apps
  homebrew_cask:
    name:
      - iterm2
      - visual-studio-code
- name: Install MacVim
  homebrew_cask:
    name: macvim
    state: present
  ignore_errors: true
