- name: Make Finder closable
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
- name: Hide Dock automatically
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
- name: Hide recents from Dock
  community.general.osx_defaults:
    domain: com.apple.Dock
    key: show-recents
    type: bool
    value: false
- name: Start key repeat sooner when a key presesd
  community.general.osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 12
- name: Navigate using tab and shift+tab anywhere
  community.general.osx_defaults:
    key: AppleKeyboardUIMode
    type: int
    value: 2
- name: Repeat key on single press and hold
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
- name: Faster key repeat
  community.general.osx_defaults:
    key: KeyRepeat
    type: int
    value: 5
- name: Show full URL in Safari
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: ShowFullURLInSmartSearchField
    type: bool
    value: true
- name: Enable Safari developer tools
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: IncludeDevelopMenu
    type: bool
    value: true
- name: Show inspect in Safari context menu
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtras
    type: bool
    value: true
- name: Enable Safari developer tools
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: WebKitDeveloperExtrasEnabledPreferenceKey
    type: bool
    value: true
- name: Enable Safari developer tools
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled
    type: bool
    value: true
- name: Remove the default hot corner
  community.general.osx_defaults:
    domain: com.apple.Dock
    key: wvous-bl-corner
    type: int
    value: 0
- name: Point and click instead of press on trackpad
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
